spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql:
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    username: sa

